version: '3.8'

services:
  rabbitmq:
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - dev.env
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    restart: unless-stopped